### ISSUE TITLE
Assets are not commited

### ISSUE THREAD

**Issue by eduyayo** [fauu/HelixEngine#2]
Hi, 
I´m trying to run the project and it crashes missing asset files:
com.badlogic.gdx.utils.GdxRuntimeException: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load file: texture-atlas/shadow.png

could you commit them, please?

**Comment by Lifok** [comment]
If you can't commit them for copyrights, could you at least tell us where to find them pls ? :D

**Comment by fauu** [comment]
Hello!
Sorry for taking so long to respond. I've included [the placeholder assets][1] that are required to run the game and the editor. I've also added some brief readmes and blender project files for the 3d models.
Closing this for now.

[1]: https://github.com/fauu/HelixEngine/tree/master/assets
